[package]
name = "workflow-task"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
keywords = ["wasm","browser","channel"]
categories = ["wasm"]
exclude = ["/.*", "/test","/macros"]
description = """

"""

[lib]
crate-type = ["cdylib", "lib"]
doctest = false

[dependencies]
workflow-core.workspace = true
workflow-task-macros.workspace = true

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
futures.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true
